const COUNTRIES = [
    { name: 'UTC', tz: 'UTC' },
    { name: 'USA', tz: 'America/New_York' },
    { name: 'Canada', tz: 'America/Toronto' },
    { name: 'Mexico', tz: 'America/Mexico_City' },
    { name: 'Brazil', tz: 'America/Sao_Paulo' },
    { name: 'Argentina', tz: 'America/Argentina/Buenos_Aires' },
    { name: 'Chile', tz: 'America/Santiago' },
    { name: 'Colombia', tz: 'America/Bogota' },
    { name: 'Peru', tz: 'America/Lima' },
    { name: 'Venezuela', tz: 'America/Caracas' },
    { name: 'Ecuador', tz: 'America/Guayaquil' },
    { name: 'Bolivia', tz: 'America/La_Paz' },
    { name: 'Uruguay', tz: 'America/Montevideo' },
    { name: 'Paraguay', tz: 'America/Asuncion' },
    { name: 'Cuba', tz: 'America/Havana' },
    { name: 'Jamaica', tz: 'America/Jamaica' },
    { name: 'UK', tz: 'Europe/London' },
    { name: 'France', tz: 'Europe/Paris' },
    { name: 'Germany', tz: 'Europe/Berlin' },
    { name: 'Italy', tz: 'Europe/Rome' },
    { name: 'Spain', tz: 'Europe/Madrid' },
    { name: 'Netherlands', tz: 'Europe/Amsterdam' },
    { name: 'Switzerland', tz: 'Europe/Zurich' },
    { name: 'Sweden', tz: 'Europe/Stockholm' },
    { name: 'Norway', tz: 'Europe/Oslo' },
    { name: 'Denmark', tz: 'Europe/Copenhagen' },
    { name: 'Finland', tz: 'Europe/Helsinki' },
    { name: 'Poland', tz: 'Europe/Warsaw' },
    { name: 'Austria', tz: 'Europe/Vienna' },
    { name: 'Belgium', tz: 'Europe/Brussels' },
    { name: 'Portugal', tz: 'Europe/Lisbon' },
    { name: 'Czech', tz: 'Europe/Prague' },
    { name: 'Hungary', tz: 'Europe/Budapest' },
    { name: 'Romania', tz: 'Europe/Bucharest' },
    { name: 'Ukraine', tz: 'Europe/Kyiv' },
    { name: 'Russia', tz: 'Europe/Moscow' },
    { name: 'Turkey', tz: 'Europe/Istanbul' },
    { name: 'Greece', tz: 'Europe/Athens' },
    { name: 'Ireland', tz: 'Europe/Dublin' },
    { name: 'Iceland', tz: 'Atlantic/Reykjavik' },
    { name: 'China', tz: 'Asia/Shanghai' },
    { name: 'Japan', tz: 'Asia/Tokyo' },
    { name: 'Korea', tz: 'Asia/Seoul' },
    { name: 'India', tz: 'Asia/Kolkata' },
    { name: 'Singapore', tz: 'Asia/Singapore' },
    { name: 'Thailand', tz: 'Asia/Bangkok' },
    { name: 'Vietnam', tz: 'Asia/Ho_Chi_Minh' },
    { name: 'Indonesia', tz: 'Asia/Jakarta' },
    { name: 'Malaysia', tz: 'Asia/Kuala_Lumpur' },
    { name: 'Philippines', tz: 'Asia/Manila' },
    { name: 'Bangladesh', tz: 'Asia/Dhaka' },
    { name: 'Myanmar', tz: 'Asia/Yangon' },
    { name: 'Cambodia', tz: 'Asia/Phnom_Penh' },
    { name: 'Laos', tz: 'Asia/Vientiane' },
    { name: 'Mongolia', tz: 'Asia/Ulaanbaatar' },
    { name: 'Nepal', tz: 'Asia/Kathmandu' },
    { name: 'Sri Lanka', tz: 'Asia/Colombo' },
    { name: 'UAE', tz: 'Asia/Dubai' },
    { name: 'Saudi Arabia', tz: 'Asia/Riyadh' },
    { name: 'Qatar', tz: 'Asia/Qatar' },
    { name: 'Kuwait', tz: 'Asia/Kuwait' },
    { name: 'Bahrain', tz: 'Asia/Bahrain' },
    { name: 'Oman', tz: 'Asia/Muscat' },
    { name: 'Iran', tz: 'Asia/Tehran' },
    { name: 'Iraq', tz: 'Asia/Baghdad' },
    { name: 'Jordan', tz: 'Asia/Amman' },
    { name: 'Lebanon', tz: 'Asia/Beirut' },
    { name: 'Israel', tz: 'Asia/Jerusalem' },
    { name: 'Pakistan', tz: 'Asia/Karachi' },
    { name: 'Afghanistan', tz: 'Asia/Kabul' },
    { name: 'Kazakhstan', tz: 'Asia/Almaty' },
    { name: 'Uzbekistan', tz: 'Asia/Tashkent' },
    { name: 'Australia', tz: 'Australia/Sydney' },
    { name: 'New Zealand', tz: 'Pacific/Auckland' },
    { name: 'Fiji', tz: 'Pacific/Fiji' },
    { name: 'Papua New Guinea', tz: 'Pacific/Port_Moresby' },
    { name: 'South Africa', tz: 'Africa/Johannesburg' },
    { name: 'Egypt', tz: 'Africa/Cairo' },
    { name: 'Nigeria', tz: 'Africa/Lagos' },
    { name: 'Kenya', tz: 'Africa/Nairobi' },
    { name: 'Ethiopia', tz: 'Africa/Addis_Ababa' },
    { name: 'Ghana', tz: 'Africa/Accra' },
    { name: 'Morocco', tz: 'Africa/Casablanca' },
    { name: 'Algeria', tz: 'Africa/Algiers' },
    { name: 'Tunisia', tz: 'Africa/Tunis' },
    { name: 'Libya', tz: 'Africa/Tripoli' },
    { name: 'Sudan', tz: 'Africa/Khartoum' },
    { name: 'Tanzania', tz: 'Africa/Dar_es_Salaam' },
    { name: 'Uganda', tz: 'Africa/Kampala' },
    { name: 'Zimbabwe', tz: 'Africa/Harare' },
];

const CITY_TO_COUNTRY = {
    'newyork': 'USA', 'nyc': 'USA', 'washington': 'USA', 'losangeles': 'USA', 'la': 'USA', 'chicago': 'USA', 'miami': 'USA', 'boston': 'USA', 'seattle': 'USA', 'sanfrancisco': 'USA',
    'toronto': 'Canada', 'vancouver': 'Canada', 'montreal': 'Canada', 'ottawa': 'Canada',
    'mexicocity': 'Mexico', 'guadalajara': 'Mexico', 'monterrey': 'Mexico',
    'saopaulo': 'Brazil', 'riodejaneiro': 'Brazil', 'brasilia': 'Brazil', 'salvador': 'Brazil',
    'buenosaires': 'Argentina', 'cordoba': 'Argentina', 'rosario': 'Argentina',
    'santiago': 'Chile', 'valparaiso': 'Chile',
    'bogota': 'Colombia', 'medellin': 'Colombia', 'cali': 'Colombia',
    'lima': 'Peru', 'cusco': 'Peru',
    'caracas': 'Venezuela', 'maracaibo': 'Venezuela',
    'quito': 'Ecuador', 'guayaquil': 'Ecuador',
    'lapaz': 'Bolivia', 'santacruz': 'Bolivia',
    'montevideo': 'Uruguay',
    'asuncion': 'Paraguay',
    'havana': 'Cuba',
    'kingston': 'Jamaica',
    'london': 'UK', 'manchester': 'UK', 'birmingham': 'UK', 'liverpool': 'UK', 'edinburgh': 'UK',
    'paris': 'France', 'marseille': 'France', 'lyon': 'France', 'nice': 'France',
    'berlin': 'Germany', 'munich': 'Germany', 'hamburg': 'Germany', 'frankfurt': 'Germany', 'cologne': 'Germany',
    'rome': 'Italy', 'milan': 'Italy', 'venice': 'Italy', 'florence': 'Italy', 'naples': 'Italy',
    'madrid': 'Spain', 'barcelona': 'Spain', 'valencia': 'Spain', 'seville': 'Spain',
    'amsterdam': 'Netherlands', 'rotterdam': 'Netherlands', 'hague': 'Netherlands',
    'zurich': 'Switzerland', 'geneva': 'Switzerland', 'bern': 'Switzerland', 'basel': 'Switzerland',
    'stockholm': 'Sweden', 'gothenburg': 'Sweden', 'malmo': 'Sweden',
    'oslo': 'Norway', 'bergen': 'Norway',
    'copenhagen': 'Denmark',
    'helsinki': 'Finland',
    'warsaw': 'Poland', 'krakow': 'Poland', 'gdansk': 'Poland',
    'vienna': 'Austria', 'salzburg': 'Austria',
    'brussels': 'Belgium', 'antwerp': 'Belgium', 'bruges': 'Belgium',
    'lisbon': 'Portugal', 'porto': 'Portugal',
    'prague': 'Czech', 'brno': 'Czech',
    'budapest': 'Hungary',
    'bucharest': 'Romania',
    'kyiv': 'Ukraine', 'kiev': 'Ukraine', 'lviv': 'Ukraine', 'odessa': 'Ukraine',
    'moscow': 'Russia', 'petersburg': 'Russia', 'stpetersburg': 'Russia', 'novosibirsk': 'Russia',
    'istanbul': 'Turkey', 'ankara': 'Turkey', 'izmir': 'Turkey',
    'athens': 'Greece', 'thessaloniki': 'Greece',
    'dublin': 'Ireland', 'cork': 'Ireland',
    'reykjavik': 'Iceland',
    'beijing': 'China', 'shanghai': 'China', 'guangzhou': 'China', 'shenzhen': 'China', 'chengdu': 'China', 'hangzhou': 'China', 'wuhan': 'China', 'xian': 'China', 'nanjing': 'China', 'chongqing': 'China',
    'tokyo': 'Japan', 'osaka': 'Japan', 'kyoto': 'Japan', 'yokohama': 'Japan', 'sapporo': 'Japan', 'fukuoka': 'Japan',
    'seoul': 'Korea', 'busan': 'Korea', 'incheon': 'Korea', 'daegu': 'Korea',
    'mumbai': 'India', 'delhi': 'India', 'newdelhi': 'India', 'bangalore': 'India', 'hyderabad': 'India', 'chennai': 'India', 'kolkata': 'India', 'pune': 'India',
    'bangkok': 'Thailand', 'chiangmai': 'Thailand', 'phuket': 'Thailand',
    'hanoi': 'Vietnam', 'hochiminh': 'Vietnam', 'saigon': 'Vietnam', 'danang': 'Vietnam',
    'jakarta': 'Indonesia', 'bali': 'Indonesia', 'surabaya': 'Indonesia', 'bandung': 'Indonesia',
    'kualalumpur': 'Malaysia', 'penang': 'Malaysia', 'johor': 'Malaysia',
    'manila': 'Philippines', 'cebu': 'Philippines', 'davao': 'Philippines',
    'dhaka': 'Bangladesh', 'chittagong': 'Bangladesh',
    'yangon': 'Myanmar', 'mandalay': 'Myanmar',
    'phnompenh': 'Cambodia', 'siemreap': 'Cambodia',
    'vientiane': 'Laos',
    'ulaanbaatar': 'Mongolia',
    'kathmandu': 'Nepal',
    'colombo': 'Sri Lanka',
    'dubai': 'UAE', 'abudhabi': 'UAE', 'sharjah': 'UAE',
    'riyadh': 'Saudi Arabia', 'jeddah': 'Saudi Arabia', 'mecca': 'Saudi Arabia', 'medina': 'Saudi Arabia',
    'doha': 'Qatar',
    'kuwaitcity': 'Kuwait',
    'manama': 'Bahrain',
    'muscat': 'Oman',
    'tehran': 'Iran', 'isfahan': 'Iran', 'shiraz': 'Iran',
    'baghdad': 'Iraq', 'basra': 'Iraq',
    'amman': 'Jordan',
    'beirut': 'Lebanon',
    'jerusalem': 'Israel', 'telaviv': 'Israel', 'haifa': 'Israel',
    'karachi': 'Pakistan', 'lahore': 'Pakistan', 'islamabad': 'Pakistan',
    'kabul': 'Afghanistan',
    'almaty': 'Kazakhstan', 'astana': 'Kazakhstan',
    'tashkent': 'Uzbekistan',
    'sydney': 'Australia', 'melbourne': 'Australia', 'brisbane': 'Australia', 'perth': 'Australia', 'adelaide': 'Australia', 'canberra': 'Australia',
    'auckland': 'New Zealand', 'wellington': 'New Zealand', 'christchurch': 'New Zealand',
    'suva': 'Fiji',
    'portmoresby': 'Papua New Guinea',
    'johannesburg': 'South Africa', 'capetown': 'South Africa', 'durban': 'South Africa', 'pretoria': 'South Africa',
    'cairo': 'Egypt', 'alexandria': 'Egypt',
    'lagos': 'Nigeria', 'abuja': 'Nigeria',
    'nairobi': 'Kenya', 'mombasa': 'Kenya',
    'addisababa': 'Ethiopia',
    'accra': 'Ghana',
    'casablanca': 'Morocco', 'marrakech': 'Morocco', 'rabat': 'Morocco',
    'algiers': 'Algeria',
    'tunis': 'Tunisia',
    'tripoli': 'Libya',
    'khartoum': 'Sudan',
    'daressalaam': 'Tanzania', 'dodoma': 'Tanzania',
    'kampala': 'Uganda',
    'harare': 'Zimbabwe',
};

module.exports = {
    COUNTRIES,
    CITY_TO_COUNTRY
};

